-- A tabela dos vídeos das telas de guia.
--
-- **Uma tabela para todas as seções, e não uma por tela.** `territorios`,
-- `guildas` e `streamers` são tabelas separadas porque são coisas diferentes;
-- vídeos de seções diferentes são a mesma coisa com uma etiqueta. Cinco
-- tabelas iguais seriam cinco migrações, cinco políticas e cinco leitores
-- fazendo o mesmo — e a sexta tela, que já se sabe que vem, obrigaria à sexta
-- tabela. Com `secao`, acrescentar uma tela é inserir linhas.
create table if not exists public.videos (
  id          bigint generated by default as identity primary key,

  -- Qual tela mostra este vídeo: `guerras`, `astrolabio`, `titulos`,
  -- `passivas`, `multicontas`. Texto livre de propósito: uma seção nova não
  -- pode custar uma migração, que é a razão de esta tabela existir assim.
  secao       text not null,

  -- O id do YouTube, não o endereço inteiro. A miniatura, o link e o
  -- incrustável derivam todos dele, e guardar o endereço convidaria as três
  -- formas de `youtube.com/watch`, `youtu.be` e `/embed` a conviverem na
  -- mesma coluna.
  youtube     text not null,

  titulo      text not null,

  -- A classe de quem grava, e só as Guerras Territoriais a usam. Vazia nas
  -- outras seções, onde o filtro por classe simplesmente não desenha.
  classe      text,

  -- Quem gravou, pelo nick do personagem — que é como esta comunidade
  -- identifica alguém. Um campo e não dois: `autor` e `personagem` seriam a
  -- mesma pessoa escrita duas vezes, e divergiriam.
  personagem  text,

  -- O dia da guerra, como data e não como texto. Texto ordenaria `10/02`
  -- antes de `9/02`, e a ordem é o que faz uma lista de guerras servir para
  -- alguma coisa.
  data        date,

  -- A linha livre por baixo do nome e da data: `Guerra Alpha x Omega`, ou o
  -- que a ocasião pedir.
  --
  -- **Um campo e não duas colunas de guilda**, por decisão do dono em
  -- 05/10/2026 contra a minha proposta. Eu tinha argumentado que colunas
  -- separadas abririam a porta a ordenar por guilda; ele tem razão em que
  -- isso é uma hipótese minha, e num painel editado à mão cada campo a mais
  -- é um campo que fica por preencher. Uma seção que não seja guerra também
  -- não teria duas guildas para dar.
  detalhes    text,

  ordem       integer not null default 0,

  -- Tirar um vídeo do ar sem o apagar. O mesmo papel que `novidades.visivel`
  -- cumpre: um vídeo que saiu do ar por engano volta com um clique.
  visivel     boolean not null default true,

  publicado_em timestamptz not null default now()
);

create index if not exists videos_secao_idx on public.videos (secao, ordem);

-- **Aberta para ler, fechada para escrever** — o mesmo arranjo do mapa de
-- guerras e pelo mesmo motivo: as linhas *são* o conteúdo da página, então o
-- anónimo lê; e acrescentar um vídeo é editar no painel, sem build, sem CI e
-- sem deploy. Nenhuma política de insert, update ou delete existe, portanto a
-- chave publicável que vai no navegador não muda nada.
alter table public.videos enable row level security;

drop policy if exists videos_leitura on public.videos;
create policy videos_leitura on public.videos
  for select to anon, authenticated using (true);

grant select on public.videos to anon, authenticated;
